#!/bin/bash
# Assembles iptables.sh from templates based on server tags defined in .tag

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TAG_FILE="$SCRIPT_DIR/.tag"
OUTPUT="$SCRIPT_DIR/iptables.sh"
TEMPLATES_DIR="$SCRIPT_DIR/templates"
USER_DIR="$SCRIPT_DIR/user"

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*" >&2; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Check .tag ──────────────────────────────────────────────────────────────

if [[ ! -f "$TAG_FILE" ]]; then
    warn "File '.tag' not found — nothing to do."
    exit 0
fi

mapfile -t TAGS < <(grep -v '^\s*[#;]' "$TAG_FILE" | grep -v '^\s*$' | awk '{print $1}')

if [[ ${#TAGS[@]} -eq 0 ]]; then
    warn "No tags found in '.tag' — nothing to do."
    exit 0
fi

info "Tags: ${TAGS[*]}"

for tag in "${TAGS[@]}"; do
    [[ -d "$TEMPLATES_DIR/$tag" ]] || error "Unknown tag '$tag' — directory 'templates/$tag' does not exist."
done

# ── Helpers ─────────────────────────────────────────────────────────────────

section() { printf '\n# ═══════════════ %s ═══════════════\n' "$*"; }
append()  { cat "$1"; printf '\n'; }

# Reads files from user/ipsets/, generates ipset create/flush/add commands.
# Each file name becomes the set name; hash:net type supports single IPs and CIDR.
# Lines starting with # are preserved as comments in the output.
# Inline comments (after the IP) are stripped before passing to ipset.
generate_ipsets() {
    local ipset_dir="$USER_DIR/ipsets"

    if [[ ! -d "$ipset_dir" ]]; then
        warn "user/ipsets/ not found — no IPsets will be created"
        return 0
    fi

    shopt -s nullglob
    local count=0

    for set_file in "$ipset_dir"/*; do
        [[ -f "$set_file" ]]           || continue
        [[ "$set_file" == *.example ]] && continue

        local set_name
        set_name="$(basename "$set_file")"
        ((count++)) || true

        printf '\n# ── IPSet: %s\n' "$set_name"
        printf '$IPS create %s hash:net -exist\n' "$set_name"
        printf '$IPS flush %s\n' "$set_name"

        while IFS= read -r line || [[ -n "$line" ]]; do
            # Preserve full-line comments
            if [[ "$line" =~ ^[[:space:]]*# ]]; then
                printf '%s\n' "$line"
                continue
            fi
            # Skip blank lines
            [[ -z "${line//[[:space:]]/}" ]] && continue
            # Strip inline comment and whitespace, add to set
            local ip="${line%%#*}"
            ip="${ip//[[:space:]]/}"
            [[ -n "$ip" ]] && printf '$IPS add %s %s -exist\n' "$set_name" "$ip"
        done < "$set_file"
    done

    if [[ $count -eq 0 ]]; then
        warn "user/ipsets/ is empty — no IPsets will be created"
    fi
}

# ── Assemble ─────────────────────────────────────────────────────────────────

{
    printf '#!/bin/bash\n'
    printf '# Generated by build.sh — %s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
    printf '# Tags: %s\n' "${TAGS[*]}"
    printf '# DO NOT EDIT — regenerate with: bash build.sh\n'
    printf 'set -euo pipefail\n'

    # 1. Constants (IPT, IPS, set names)
    section "CONSTANTS"
    append "$TEMPLATES_DIR/general/10-vars.sh"

    # 2. Server-specific variables (WAN, WAN_IP, ports, etc.)
    if [[ -f "$USER_DIR/.env" ]]; then
        section "SERVER ENVIRONMENT  [user/.env]"
        append "$USER_DIR/.env"
    else
        warn "user/.env not found — WAN, WAN_IP, PORT_APP and other server vars are undefined"
    fi

    # 2.1 Validate required variables — fail fast before touching any rules
    section "PREFLIGHT CHECK"
    printf '%s\n' \
        ': "${WAN:?WAN is not set — run detect-wan.sh or configure in user/.env}"'

    # 3. IPSet: create, flush, and populate from user/ipsets/ files
    section "IPSET SETUP  [user/ipsets/]"
    generate_ipsets

    # 4. General base rules (30-flush through 90-ssh, sorted)
    section "GENERAL RULES"
    shopt -s nullglob
    for f in "$TEMPLATES_DIR/general"/[3-9][0-9]-*.sh; do
        append "$f"
    done

    # 5. Tag-specific rules (sorted within each tag directory)
    for tag in "${TAGS[@]}"; do
        section "TAG: $tag"
        shopt -s nullglob
        for f in "$TEMPLATES_DIR/$tag"/[0-9]*.sh; do
            append "$f"
        done
    done

    # 6. User custom rules (port forwards, extra rules, etc.)
    if [[ -f "$USER_DIR/custom.sh" ]]; then
        section "USER CUSTOM RULES  [user/custom.sh]"
        append "$USER_DIR/custom.sh"
    fi


} > "$OUTPUT"

chmod +x "$OUTPUT"
info "Generated: $OUTPUT"
info "Review and apply with: sudo bash $OUTPUT"
